- model: qwen-plus
  api_key: sk-ws-H.EDHPYXH.T53V.MEQCIF2pqFu7scnbobYlfnqHCsTI0G3NjPdV-YZ7zvVLDxfIAiBzkoNic7q_z_COGl6HKkgAZWJxIeqy_6xg1YFl0l-DkQ
  enable_thinking: false
  temperature: 1.5
  url: https://ws-850165j19tm42mwu.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/chat/completions
  stream: false
  timeout: 60
  max_tokens: 512
- model: Qwen/Qwen3-8B
  api_key: sk-mdhvlpnkdmpmokrvkhqhxttktoaocwyhrqbtogrghupwhuxa
  enable_thinking: false
  temperature: 0.7
  url: https://api.siliconflow.cn/v1/chat/completions
  timeout: 60
  stream: false
  max_tokens: 512
- model: openpangu-2.0-flash
  api_key: R_Jm0ajr_TzY1oanHZdzvEvpVEjh1MlDJaYOMnHXAgnvtLmfGGOyz7VidzDzPbW6Ge2h3wZ_pu-4CYBq-RU0Fg
  enable_thinking: false
  temperature: 0.7
  url: https://api.modelarts-maas.com/v2/chat/completions
  timeout: 60
  stream: false
  max_tokens: 512
