- model: qwen-plus
  api_key: sk-ws-H.EDHPYXH.T53V.MEQCIF2pqFu7scnbobYlfnqHCsTI0G3NjPdV-YZ7zvVLDxfIAiBzkoNic7q_z_COGl6HKkgAZWJxIeqy_6xg1YFl0l-DkQ
  enable_thinking: false
  temperature: 1.5
  url: https://ws-850165j19tm42mwu.cn-beijing.maas.aliyuncs.com/compatible-mode/v1/chat/completions
  stream: false
  timeout: 60
  max_tokens: 512
- model: glm-5
  api_key: sk-sp-2b8eceec7095436696d234ce0e51a491
  enable_thinking: false
  temperature: 0.7
  url: https://coding.dashscope.aliyuncs.com/v1/chat/completions
  timeout: 60
  stream: false
  max_tokens: 512
- model: kimi-k2.5
  api_key: sk-sp-2b8eceec7095436696d234ce0e51a491
  enable_thinking: false
  temperature: 0.7
  url: https://coding.dashscope.aliyuncs.com/v1/chat/completions
  timeout: 60
  stream: false
  max_tokens: 512
